welcome.dimmer <- function(){
  'DiMmer is a tool created for the analysis of methylation data generated by Illumina Infinium HumanMethy-
  lation450 BeadChip (450k) and Illumina Infinium HumanMethylation EPIC BeadChip (850k, EPIC). Its com-
  mand line version can also take whole genome bisulfite sequencing as input, in the form of Bismarks .cov
  files, <b>which is available through this webapp</b>. It performs data preprocessing with all the steps 
  of the typical pipeline, such as quality control, normalization and data filtering. The main contribution 
  of DiMmer is the implementation of differential analysis between two conditions, from the detection of 
  differentially methylated probes to entire differentially methylated regions (DMRs), providing, in addition, 
  the genes who are mapped to the regions. <br>
  The tool offers multiple statistical testing for results evaluation and, furthermore, it provides the option of blood 
  cells composition estimation. <br>'
}

idat.info <- function(){
  '<b> Important: </b><br>
  The raw .idat files are expected to be at one of two places, relative to the uploaded sample annotation file: <br>
  The first option is, that all .idat files are in the same directory as the sample annotation file, the second one is, that they are in sub-directories with the same name as their Sentrix ID.<br>
  For a detailed example, please check the user manual.'
}

beta.info <- function(){
  '<b> Important: </b><br>
  The beta-value matrix input offers three different subtypes: A beta-matrix originating from a 450k array, from a 850k/EPIC array of a completely custom matrix. The format of the sample annotation file depends on the chosen subtype.<br>
  For detailed examples for all three options, please check the user manual.'
}

bisulfite.info <- function(){
  '<b> Important: </b><br>
  The whole genome bisulfite sequencing input needs the absolute or relative path to all input files contained in the sample column of the sample annotation file. <br>
  For a detailed example, please check the user manual.'
}

model.warning <- function(){
  '<font color="red"> Regression is not possible when using paired data! </font>  '
}

upload.info <- function(){
  '<b> Upload Information: </b><br>
  DiMmer UI expects you to have uploaded an annotation file in the configuration tab prior to uploading methylation data. <br><br>
  All necessary input files need to be combined into one compressed archive, .zip and .tar.gz is accepted.<br>
  '
}