proxy:
  port: 8080
  landing-page: /app/dimmerui
  authentication: none
  admin-groups: admins
  container-log-path: ./container-logs
  container-backend: docker
  port-range-start: 20000
  port-range-max: 20049
  container-wait-time: 10000
  heartbeat-rate: 1000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 6000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)
  hide-navbar: true
  users:
  - name: jack
    password: password
    groups: admins
  docker:
    internal-networking: true
  specs:
  - id: dimmerui
    display-name: Dimmer UI
    description: Webapp to configurate and run DiMmer
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/R/', host = '0.0.0.0', port = 3838)"]
    container-network: dimmerui_sp-net
    container-image: dimmerui:latest

logging:
  file:
    name: ./shinyproxy.log

server:
  useForwardHeaders: true